channels:
    - conda-forge
    - defaults
    - bioconda
dependencies:
    - numpy==1.15.4
    - scipy==1.1.0
    - cython==0.28.5
    - matplotlib==3.0.0
    - seaborn==0.9.0
    - bokeh==0.13.0
    - pandas==0.23.4
    - h5py==2.8.0
    - numba==0.40.0
    - dask==0.19.3
    - cytoolz==0.9.0.1
    - ipython==7.0.1
    - jupyter==1.0.0
    - ipywidgets==7.4.2
    - parallel
    - pbgzip
    - samtools>=1.4
    - sra-tools>=2.8.1
    - fastqc==0.11.8
    - bwa==0.7.17
    - ucsc-bigwigtobedgraph
    - ucsc-bedgraphtobigwig
    - ucsc-fetchchromsizes
    - bedtools==2.27.1
    - biopython
    - pyfaidx==0.5.4.1
    - pysam==0.15.0
    - pairix
    - pbgzip
    - coreutils
    - pip:
        - git+https://github.com/mirnylab/pairsamtools
        - git+https://github.com/mirnylab/cooltools
        - git+https://github.com/nvictus/lavaburst.git
        - git+https://github.com/nvictus/pybbi@e8a6ea750860ceb9f125f2366393cb0c11b1f1fc
        - bioframe==0.0.7
        - cooler==0.7.6
        - multiprocess==0.70.6.1
        - awscli==1.16.31
        - s3fs==0.1.6
       
